using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Application;
using Application.Common.Exceptions;
using Application.Common.Interfaces.Hubs;
using Application.Prizes.Common;
using NSwag.Generation.Processors;
using NSwag.Generation.Processors.Contexts;

/// <summary>
/// Add missing models / enums to be generated by Nswag.
/// Generally all models connected to Controllers are automatically mapped.
/// </summary>

namespace Web.DocumentProcessors
{
  public class CustomDocumentProcessor : IDocumentProcessor
  {
    public void Process(DocumentProcessorContext context)
    {
      AddTypeToSchema(context, typeof(CommandErrorCode));
      AddTypeToSchema(context, AllHubsTypeGenerator.Generate());
    }

    private void AddTypeToSchema(DocumentProcessorContext context, Type type)
    {
      if (!context.SchemaResolver.HasSchema(type, true))
      {
        context.SchemaGenerator.Generate(type, context.SchemaResolver);
      }
    }
  }
}
