name: Full Frontend Build, Format, and Test

on:
  pull_request:
    paths:
      - "frontend/**"
    branches:
      - main

defaults:
  run:
    working-directory: frontend

env:
  node-version: 14

jobs:
  build:
    name: Full build validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"

      - run: npm install

      - run: npm run validate

  codecov:
    name: CodeCov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"

      - run: npm install

      - run: npm test

      - name: Run CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          working-directory: frontend
